### ISSUE TITLE
Describe data analisys

### ISSUE THREAD

**Issue by TheLastGimbus** [TinXsat/project-structure#19]
@miki164 has done some progress lately with this, so please add a few words about it. Maybe just short describtion and link to https://github.com/TinXsat/data-processing-algorithms , where will be more details

**Comment by TheJimmyNowak** [comment]
Ohh I haven't been here from a long time. 
Well I today worked with open drone maps and I think that can help us to analyse data. Actually it will help with the hardest part of data analysis. Although I have to write preprocessing algorithms to preprocess data.

On the other hand I'm worried a little due to poor quality of photos from cansat. But I don't care LMAO. We will see in tests if it is something to worry about.
