### ISSUE TITLE
Describe electrical/hardwere aspects of satellite

### ISSUE THREAD

**Issue by TheLastGimbus** [TinXsat/project-structure#8]
@Fifi-fifi and @miki164 will describe inner workings of our satellite

**Comment by TheJimmyNowak** [comment]
# General architecture
Primary requirements for electronics in Cansat:
* Usage of double/triple redundancy for each physical component to improve fail-safe operation and robustness. 
* Accurate measurement of several electrical parameters inside the system in order to provide information about possible failures and their sources.
* Usage of low-cost widely available, off-the-shelf components to allow for decreased budget on electronics part and make it more affordable.
* Physically robust construction of PCB. 

To answer all needs a versatile digital control is required. This leads to the use of a microcontroller as main controller. Acquisition and interpretation of different kinds of data requires speed and plenty of memory. Modern Uc's with 32 bit cores are extremely low-cost, fast and have a lot of useful pheripherials.  

Reliability and redundancy, used widely in self-driving cars, are main challenges to deal with, while keeping cost as low as possible. To improve  MTBF (mean time between failures) all parts of the system will have hardware support for self-testing.

More description soon

**Comment by TheLastGimbus** [comment]
@Fifi-fifi @Przemek937 @miki164 what's up with this? Could someone finally PR?

**Comment by TheJimmyNowak** [comment]
Nope.

**Comment by TheLastGimbus** [comment]
XD
